import { useEffect, useState } from 'react';
import { Alert, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRoute } from '@react-navigation/native';
import { Button } from '@/components/Button';
import { useAIPlayground, useAIProviders, useAITaskConfigs, useOCRSettings, usePromptTemplates, useSaveAIProvider, useSaveAITaskConfig, useSaveOCRSettings, useSavePromptTemplate, useSaveUsageLimit, useUsageLimits } from '@/services/queries';
import { colors } from '@/theme/colors';

const TASKS = ['AI_SEARCH', 'AI_ASSISTANT', 'OCR_PARSE', 'ANALYTICS_SLOWMOVING', 'PROMOTION_SUGGEST', 'REVIEW_SUMMARY', 'CONTENT_GENERATION', 'RESTOCK_SUGGEST'];
const titles: Record<string, string> = { provider: 'Sửa provider', tasks: 'Task & Fallback', ocr: 'OCR Settings', prompts: 'Prompt Templates', playground: 'Test Playground', usage: 'Usage & Cost Limit' };

export function AISettingsScreen() {
  const route = useRoute<any>(); const section = route.params?.section ?? 'tasks'; const provider = route.params?.provider;
  const providers = useAIProviders().data ?? []; const tasks = useAITaskConfigs().data ?? []; const ocrQ = useOCRSettings(); const templates = usePromptTemplates().data ?? []; const limits = useUsageLimits().data ?? [];
  const saveProvider = useSaveAIProvider(); const saveTask = useSaveAITaskConfig(); const saveOcr = useSaveOCRSettings(); const savePrompt = useSavePromptTemplate(); const saveLimit = useSaveUsageLimit(); const playground = useAIPlayground();
  const [form, setForm] = useState<any>({}); const [prompt, setPrompt] = useState(''); const [taskType, setTaskType] = useState('AI_ASSISTANT'); const [result, setResult] = useState('');
  useEffect(() => { if (section === 'provider') setForm({ name: provider?.name ?? '', type: provider?.type ?? 'MOCK', baseUrl: provider?.baseUrl ?? '', defaultModel: provider?.defaultModel ?? '', status: provider?.status ?? 'ACTIVE' }); if (section === 'ocr' && ocrQ.data) setForm(ocrQ.data); }, [section, provider, ocrQ.data]);
  const input = (key: string, label: string, multiline = false) => <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput style={[styles.input, multiline && styles.multiline]} value={String(form[key] ?? '')} onChangeText={(value) => setForm({ ...form, [key]: value })} multiline={multiline} /></View>;
  const notify = (error: any) => Alert.alert('Không thể lưu', error?.response?.data?.message ?? 'Vui lòng thử lại.');
  let content;
  if (section === 'provider') content = <>{input('name', 'Tên')}{input('type', 'Loại (DEEPSEEK / OPENAI_COMPATIBLE / MOCK)')}{input('baseUrl', 'Base URL')}{input('defaultModel', 'Model mặc định')}<Button title="Lưu provider" fullWidth loading={saveProvider.isPending} onPress={async () => { try { await saveProvider.mutateAsync({ id: provider?.id, dto: form }); Alert.alert('Đã lưu', 'Provider đã được cập nhật.'); } catch (e) { notify(e); } }} /></>;
  else if (section === 'ocr') content = <>{input('engine', 'Engine (MOCK / PADDLEOCR / EASYOCR)')}{input('fallbackEngine', 'Fallback engine')}{input('confidenceThreshold', 'Ngưỡng confidence')}<Button title="Lưu OCR settings" fullWidth loading={saveOcr.isPending} onPress={async () => { try { await saveOcr.mutateAsync({ ...form, confidenceThreshold: Number(form.confidenceThreshold ?? 0) }); Alert.alert('Đã lưu', 'OCR settings đã cập nhật.'); } catch (e) { notify(e); } }} /></>;
  else if (section === 'prompts') content = <>{input('name', 'Tên template')}{input('taskType', 'Task type')}{input('systemPrompt', 'System prompt', true)}<Button title="Lưu prompt template" fullWidth loading={savePrompt.isPending} onPress={async () => { try { await savePrompt.mutateAsync({ ...form, taskType: form.taskType || taskType }); Alert.alert('Đã lưu', 'Prompt template đã cập nhật.'); } catch (e) { notify(e); } }} />{templates.map((t: any) => <Text key={t.id} style={styles.row}>{t.taskType} · {t.name}</Text>)}</>;
  else if (section === 'playground') content = <><Text style={styles.label}>Task type</Text><TextInput style={styles.input} value={taskType} onChangeText={setTaskType} /><TextInput style={[styles.input, styles.multiline]} value={prompt} onChangeText={setPrompt} placeholder="Nhập prompt để test" multiline /><Button title="Chạy test" fullWidth loading={playground.isPending} onPress={async () => { try { const response = await playground.mutateAsync({ taskType, prompt, providerId: provider?.id }); setResult(response.text ?? JSON.stringify(response.data)); } catch (e) { notify(e); } }} />{!!result && <Text style={styles.result}>{result}</Text>}</>;
  else if (section === 'usage') content = <>{providers.map((p: any) => { const limit = limits.find((l: any) => l.scope === `provider:${p.id}`); return <View key={p.id} style={styles.card}><Text style={styles.row}>{p.name}</Text><TextInput style={styles.input} placeholder="Ngân sách USD/tháng" keyboardType="decimal-pad" value={String(limit?.monthlyCostLimitUsd ?? '')} onChangeText={(value) => setForm({ ...form, [p.id]: value })} /><Button title="Lưu limit" size="sm" loading={saveLimit.isPending} onPress={() => void saveLimit.mutateAsync({ providerId: p.id, monthlyCostLimitUsd: Number(form[p.id] ?? limit?.monthlyCostLimitUsd ?? 0), isEnforced: true }).catch(notify)} /></View>; })}</>;
  else content = <>{tasks.map((task: any) => <View key={task.id} style={styles.card}><Text style={styles.row}>{task.taskType}</Text><Text style={styles.small}>{task.primaryProvider?.name ?? 'System default'} → fallback {task.fallbackProvider?.name ?? 'Mock'}</Text><Button title="Dùng provider đầu tiên" size="sm" onPress={() => void saveTask.mutateAsync({ taskType: task.taskType, primaryProviderId: providers[0]?.id, fallbackProviderId: providers.find((p: any) => p.type === 'MOCK')?.id, mode: 'HYBRID' }).catch(notify)} /></View>)}{tasks.length === 0 && TASKS.map((taskType) => <Button key={taskType} title={`Tạo ${taskType}`} size="sm" onPress={() => void saveTask.mutateAsync({ taskType, primaryProviderId: providers[0]?.id, fallbackProviderId: providers.find((p: any) => p.type === 'MOCK')?.id, mode: 'HYBRID' }).catch(notify)} />)}</>;
  return <SafeAreaView style={styles.container} edges={['bottom']}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>{titles[section]}</Text>{content}</ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: colors.bgSecondary }, content: { padding: 16, gap: 12 }, title: { fontSize: 21, fontWeight: '800', color: colors.text }, field: { gap: 5 }, label: { color: colors.textSecondary, fontSize: 12 }, input: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: 10, color: colors.text, padding: 11 }, multiline: { minHeight: 120, textAlignVertical: 'top' }, card: { padding: 12, borderRadius: 10, backgroundColor: colors.surface, gap: 8 }, row: { fontWeight: '700', color: colors.text }, small: { fontSize: 12, color: colors.textSecondary }, result: { padding: 12, borderRadius: 10, backgroundColor: colors.surface, color: colors.text } });
